### ISSUE TITLE
Typings need some love

### ISSUE THREAD

**Issue by setheen** [auth0/auth0.js#136]
Two issues but I'm hitting them both here in case I'm missing something simple.

- My ide cannot find the type definitions for auth0-js because it's defined as "auth0"
```shell
npm install auth0-js --save
typings install auth0 --save --ambient
```
```javascript
import * as Auth0 from 'auth0-js';
```

The exported typings module is named "auth0" while the npm package is "auth0-js".  I get around this problem by tweaking the bottom of index.d.ts to ```declare module "auth0-js" { ...``` but it's not ideal.

- The type definition for Auth0Static.getDelegationToken vs implementation do not match

Definition
```typescript
interface Auth0Static {
    getDelegationToken(targetClientId: string, id_token: string, options: any, callback: (error?: Auth0Error, delegationResult?: Auth0DelegationToken) => any): void;
}
```

Implementation
```javascript
Auth0.prototype.getDelegationToken = function (options, callback) {...
```

Would love to be told I'm making a stupid mistake

**Comment by rrahlf** [comment]
To complicate matters, Typings has gone 1.0 and has some breaking changes. 

`typings install auth0 --save --ambient`

is now

`typings install dt~auth0 --save --global`

and the folder structure inside the typings folder has changed (making the problem with editing auth0/index.d.ts immediately apparent).

Watching this thread.

**Comment by npradeeptha** [comment]
Anyone has a workaround for this?

**Comment by westy92** [comment]
I've begun work on this here: https://github.com/westy92/DefinitelyTyped/tree/fix-auth0.

**Comment by westy92** [comment]
My PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10653) was just merged.  This should now be fixed!

**Comment by rl-dmay** [comment]
This just caused me a world of pain. @westy92 one of the issues mentioned in the OP is still not fixed with your PR:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f5a12116d0eb27ec1d4e8a1a0730957efbdba3e9/auth0-js/auth0-js.d.ts#L130

the module is still exported as "auth0" when it should be "auth0-js"

**Comment by westy92** [comment]
I somehow missed that string.  I'll submit a PR shortly.

**Comment by westy92** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10721

**Comment by rl-dmay** [comment]
Thanks. There are actually a number of other issues with the typings file, once I've completed my implementation I'll share.

**Comment by rbuckton** [comment]
As I mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10721#issuecomment-242801261, there are *two* packages for auth0, so both `auth0` and `auth0-js` are equally valid.

**Comment by CrisLi** [comment]
I still get this error after I install types

`npm install auth0-js --save`
`npm install @types/auth0-js --save`

```typescript
   import { Auth0 } from 'auth0-js';
```

`Module '"auth0-js"' has no exported member 'Auth0'.`

**Comment by westy92** [comment]
@CrisLi there is no `Auth0` class.  Try: 
```ts
import * as Auth0 from 'auth0-js';
```

**Comment by CrisLi** [comment]
@westy92  I have tried 

```js
import * as Auth0 from 'auth0-js';
```

The error became 

`node_modules/@types/auth0-js/index.d.ts' is not a module.`

The `package.json` snippet is:

```
    "@types/auth0-js": "^8.1.0",
    "angular2-jwt": "^0.1.28",
    "auth0-js": "^8.2.0",
```

**Comment by csvn** [comment]
I have the same issue as @CrisLi. I was able to fix it locally by changing the top line from:
```typescript
declare module auth0 {
```
to
```typescript
declare module 'auth0-js' {
```
Not sure how this affects backwards compatibility or if there are any other issues.

For now, I did the following to make the typings work:
1. Added `"typeRoots": ["./types"]` to `tsconfig.json`
2. Moved `index.d.ts` from `node_modules/@types/auth0-js` to `types/auth0-js`
3. Fixed the `index.d.ts` file
4. Removed `node_modules/@types/auth0-js`

The above steps require TS >v.2.0.0 and possibly modeResulotion set to `node`.

**Comment by westy92** [comment]
I was looking through this trying to figure out the issue, and it looks like it may have been fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/625be7cb6522b3d004b2fe93ace7357686eeb3a4.  Can you grab the latest version (8.3.0) and try again?

I fixed this issue in v7 but it appears to have regressed in earlier versions of v8.
