### ISSUE TITLE
global is not defined Angular 6

### ISSUE THREAD

**Issue by lucax88x** [auth0/auth0.js#753]
Using any browser, by just performing a login with this library we get this error:

![image](https://user-images.githubusercontent.com/6294464/39647358-e7658aa6-4fde-11e8-940b-9211d6b9db27.png)

**Comment by lucax88x** [comment]
as temporary workaround for any that reach this page you can add

` (window as any).global = window;`

in polyfill.ts

**Comment by luisrudge** [comment]
Thanks for the workaround. At this point, the angular community will have to come with a solution for this problem, since we're hardly the only library using `global`. This was already discussed in #748. Moving away from using global means a huge refactor in auth0.js and it's not something we'll actively work on in the near future.

**Comment by luisrudge** [comment]
More context on the angular change here: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by luisrudge** [comment]
@fetis I think this is a bigger change than you think, but if you want to go for it, I'll review and test your PR 🎉

**Comment by tinyweasel** [comment]
Workaround doesn't workaround for me.

**Comment by fetis** [comment]
@tinyweasel you don't need workaround anymore. it's fixed since  v9.6.1

**Comment by tinyweasel** [comment]
I just upgraded to Angular 7 and it's happening to me though. What should I update to fix it?

**Comment by jayzhou3** [comment]
// app/app.js

```
import Application from '@ember/application';
import Resolver from './resolver';
import loadInitializers from 'ember-load-initializers';
import config from './config/environment';

window.global = window; //add this to your app.

const App = Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver
});

loadInitializers(App, config.modulePrefix);

export default App;
```

**Comment by ram4420** [comment]
i had same issue i just tried "npm install" it shows another error
"Error on Content Security Policy directive"
i was just added (window as any).global = window; in polyfilles.ts
now its working fine.

**Comment by JobyCheriyan** [comment]
I too faced this issue after following an online training session, I resolved it by removing following element <router-outlet></router-outlet> from "app.component.html"

**Comment by fetis** [comment]
@jayzhou3 @ram4420  the original issue originates to Angular and it was fixed. If you have an issue with other frameworks plz open another ticket and don't pollute this one.

**Comment by jayzhou3** [comment]
> @jayzhou3 @ram4420 the original issue originates to Angular and it was fixed. If you have an issue with other frameworks plz open another ticket and don't pollute this one.

I think, so it only fix on the angular but it does not fix on Emberjs, Vuejs, Reactjs ... etc...

**Comment by fetis** [comment]
> I see, so it only fix on the angular but it does not fix on Emberjs, Vuejs, Reactjs ... etc...
in my opinion, it should, but I don't know your environment and lib versions and can't help you to test it because I'm not familiar with Ember

**Comment by nharrer** [comment]
In my case (Angular 8.1.2 and ionic 4.7.1) not only global was missing but also `Buffer `and `process`. I had to add following lines to the end of polyfills.ts:

```
// auth0 needs this
(window as any).global = window;
// @ts-ignore
window.Buffer = window.Buffer || require('buffer').Buffer;
// @ts-ignore
window.process = window.process || { version: "" }
```

**Comment by vdavyskiba** [comment]
Workaround for me is to add bundle to index.html
<script src="https://cdn.auth0.com/js/lock/11.14.1/lock.min.js"></script>
instead of import 'auth0-lock' in .ts file
